import React, { useState } from 'react';
import { FileText, Copy, Check, Download } from 'lucide-react';

export default function RcaViewer({ rcaMarkdown, incidentCode }) {
  const [copied, setCopied] = useState(false);

  if (!rcaMarkdown) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(rcaMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([rcaMarkdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `post-mortem-${incidentCode || 'incident'}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900/80 overflow-hidden">
      
      {/* Header Bar */}
      <div className="px-5 py-3 border-b border-slate-800 bg-slate-950/60 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2.5">
          <div className="p-1.5 rounded-lg bg-slate-800 border border-slate-700/60 text-cyan-400">
            <FileText className="w-4 h-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-xs font-semibold text-slate-100">
                Post-Mortem Root Cause Analysis (RCA)
              </h3>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                SRE Standard
              </span>
            </div>
            <span className="text-[11px] text-slate-500 font-mono">
              Auto-synthesized post incident resolution
            </span>
          </div>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-mono font-medium transition-colors border ${
              copied 
                ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30' 
                : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border-slate-700'
            }`}
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
            <span>{copied ? 'Copied' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-mono font-medium bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 transition-colors"
          >
            <Download className="w-3.5 h-3.5 text-slate-400" />
            <span>Download</span>
          </button>
        </div>
      </div>

      {/* Markdown Document Content */}
      <div className="p-5 bg-slate-950/80 overflow-x-auto text-slate-200 text-xs leading-relaxed select-text">
        <pre className="font-mono text-xs whitespace-pre-wrap leading-relaxed text-slate-300 bg-slate-900/60 p-4 rounded-lg border border-slate-800">
          {rcaMarkdown}
        </pre>
      </div>

      {/* Footer */}
      <div className="px-5 py-2.5 border-t border-slate-800/80 bg-slate-950/40 flex items-center justify-between text-[11px] text-slate-500 font-mono">
        <span>Generated by OpsSentinel Multi-Agent Fleet</span>
        <span>Audit Status: Archived to SQLite</span>
      </div>

    </div>
  );
}
